# Generated by Django 2.2.3 on 2019-12-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_member_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
